export {
  CommandReceiptSchema,
  DailyReviewRecordSchema,
  DecisionOptionRecordSchema,
  DecisionRecordSchema,
  DecisionReviewOutcomeSchema,
  DecisionReviewRecordSchema,
  DecisionStatusSchema,
  JourneyEntryRecordSchema,
  FocusAreaRecordSchema,
  MilestoneIntentSnapshotSchema,
  MilestoneRecordSchema,
  QuarterIntentSnapshotSchema,
  QuarterRecordSchema,
  SessionRecordSchema,
  TaskLifecycleEventRecordSchema,
  TaskPlanSnapshotSchema,
  TaskRecordSchema,
  UserRecordSchema,
  type CommandReceipt,
  type DailyReviewRecord,
  type DecisionOptionRecord,
  type DecisionRecord,
  type DecisionReviewRecord,
  type JourneyEntryRecord,
  type FocusAreaRecord,
  type MilestoneIntentSnapshot,
  type MilestoneRecord,
  type QuarterIntentSnapshot,
  type QuarterRecord,
  type SessionRecord,
  type TaskLifecycleEventRecord,
  type TaskPlanSnapshot,
  type TaskRecord,
  type UserRecord,
  AuthRoleSchema,
  PasswordVerifierSchema,
  TotpSecretCipherSchema,
  AccountRecordSchema,
  AuthInviteRecordSchema,
  AuthSessionRecordSchema,
  MediaRecordSchema,
  EmailPreferenceRecordSchema,
  type AuthRole,
  type PasswordVerifier,
  type TotpSecretCipher,
  type AccountRecord,
  type AuthInviteRecord,
  type AuthSessionRecord,
  type MediaRecord,
  type EmailPreferenceRecord,
} from "./journey-records.js";
export { JourneyStateSchema, type JourneyState } from "./journey-state-schema.js";
export { projectTaskStatus, validateJourneyState } from "./journey-state-validation.js";

import type { JourneyState } from "./journey-state-schema.js";

export function createNoHistorySeed(writtenAt: string): JourneyState {
  return {
    schemaVersion: 1,
    storeRevision: 0,
    writtenAt,
    records: {
      users: {
        "local-user": {
          id: "local-user",
          name: "Ali",
          timeZone: "Europe/Amsterdam",
          createdAt: writtenAt,
        },
      },
      quarters: {},
      focusAreas: {},
      milestones: {},
      tasks: {},
      sessions: {},
      taskLifecycleEvents: {},
      dailyReviews: {},
      journeyEntries: {},
      decisionRecords: {},
      decisionReviews: {},
      aiReviews: {},
    },
    commandReceipts: {},
  };
}
